// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQU8-Ul8zKMGbpatGSEjmIey0f6atWKHM',
    appId: '1:581570472280:web:886cfd88d69e973b5f1d2d',
    messagingSenderId: '581570472280',
    projectId: 'flutter-crud-cd108',
    authDomain: 'flutter-crud-cd108.firebaseapp.com',
    databaseURL: 'https://flutter-crud-cd108-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-cd108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vs9cqVmRijQCISjqJ5NgXGXaWZHeVaA',
    appId: '1:581570472280:android:402c69e450c5b9d15f1d2d',
    messagingSenderId: '581570472280',
    projectId: 'flutter-crud-cd108',
    databaseURL: 'https://flutter-crud-cd108-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-cd108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXibIT6OM73j0eT_xd28hi-B59puQnT04',
    appId: '1:581570472280:ios:7fa855bcbf4d51ef5f1d2d',
    messagingSenderId: '581570472280',
    projectId: 'flutter-crud-cd108',
    databaseURL: 'https://flutter-crud-cd108-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-cd108.appspot.com',
    iosClientId: '581570472280-a12mubbccf71p9ggbf6tsvfaaej7tt6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXibIT6OM73j0eT_xd28hi-B59puQnT04',
    appId: '1:581570472280:ios:7fa855bcbf4d51ef5f1d2d',
    messagingSenderId: '581570472280',
    projectId: 'flutter-crud-cd108',
    databaseURL: 'https://flutter-crud-cd108-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-cd108.appspot.com',
    iosClientId: '581570472280-a12mubbccf71p9ggbf6tsvfaaej7tt6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageDesign',
  );
}
